-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 01:59:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_SIBCATIE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_SIBCATIE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_SIBCATIE` DEFAULT CHARACTER SET utf8 ;
USE `BD_SIBCATIE` ;

-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Forma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Forma` (
  `idForma` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `caracteristicas` VARCHAR(255) NULL,
  PRIMARY KEY (`idForma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`EstadoSalud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`EstadoSalud` (
  `idEstadoSalud` INT NOT NULL,
  `nombre_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoSalud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Color` (
  `idColor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`TipoHoja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`TipoHoja` (
  `idTipoHoja` INT NOT NULL,
  `nombre_hoja` VARCHAR(45) NULL,
  `forma` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoHoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`ZonaCardinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`ZonaCardinal` (
  `idZonaCardinal` INT NOT NULL,
  `nombre_cardinal` VARCHAR(45) NULL,
  PRIMARY KEY (`idZonaCardinal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Continente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Continente` (
  `idContinente` INT NOT NULL,
  `nombre_continente` VARCHAR(45) NULL,
  `ZonaCardinal_idZonaCardinal` INT NOT NULL,
  PRIMARY KEY (`idContinente`, `ZonaCardinal_idZonaCardinal`),
  INDEX `fk_Continente_ZonaCardinal1_idx` (`ZonaCardinal_idZonaCardinal` ASC),
  CONSTRAINT `fk_Continente_ZonaCardinal1`
    FOREIGN KEY (`ZonaCardinal_idZonaCardinal`)
    REFERENCES `BD_SIBCATIE`.`ZonaCardinal` (`idZonaCardinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Familia` (
  `idFamilia` INT NOT NULL,
  `nombre_familia` VARCHAR(45) NULL,
  PRIMARY KEY (`idFamilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`DeterminadaPor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`DeterminadaPor` (
  `idDeterminadaPor` INT NOT NULL,
  `nombre_determinada` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idDeterminadaPor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Epiteto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Epiteto` (
  `idEpiteto` INT NOT NULL,
  `nombre_epiteto` VARCHAR(45) NULL,
  `referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idEpiteto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Genero` (
  `idGenero` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`NombreCientifico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`NombreCientifico` (
  `idNombreCientifico` INT NOT NULL,
  `Epiteto_idEpiteto` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`idNombreCientifico`, `Epiteto_idEpiteto`, `Genero_idGenero`),
  INDEX `fk_NombreCientifico_Epiteto1_idx` (`Epiteto_idEpiteto` ASC),
  INDEX `fk_NombreCientifico_Genero1_idx` (`Genero_idGenero` ASC),
  CONSTRAINT `fk_NombreCientifico_Epiteto1`
    FOREIGN KEY (`Epiteto_idEpiteto`)
    REFERENCES `BD_SIBCATIE`.`Epiteto` (`idEpiteto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NombreCientifico_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `BD_SIBCATIE`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Planta` (
  `idPlanta` INT NOT NULL,
  `fecha_ingreso` DATE NULL,
  `fuente_informacion` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `altura` DECIMAL NULL,
  `reproduccion` TINYINT NULL,
  `visible` TINYINT NULL,
  `Forma_idForma` INT NOT NULL,
  `EstadoSalud_idEstadoSalud` INT NOT NULL,
  `Color_idColor` INT NOT NULL,
  `TipoHoja_idTipoHoja` INT NOT NULL,
  `Continente_idContinente` INT NOT NULL,
  `ZonaCardinal_idZonaCardinal` INT NOT NULL,
  `Familia_idFamilia` INT NOT NULL,
  `DeterminadaPor_idDeterminadaPor` INT NOT NULL,
  `NombreCientifico_idNombreCientifico` INT NOT NULL,
  PRIMARY KEY (`idPlanta`, `Forma_idForma`, `EstadoSalud_idEstadoSalud`, `Color_idColor`, `TipoHoja_idTipoHoja`, `Continente_idContinente`, `ZonaCardinal_idZonaCardinal`, `Familia_idFamilia`, `DeterminadaPor_idDeterminadaPor`, `NombreCientifico_idNombreCientifico`),
  INDEX `fk_Planta_Forma1_idx` (`Forma_idForma` ASC),
  INDEX `fk_Planta_EstadoSalud1_idx` (`EstadoSalud_idEstadoSalud` ASC),
  INDEX `fk_Planta_Color1_idx` (`Color_idColor` ASC),
  INDEX `fk_Planta_TipoHoja1_idx` (`TipoHoja_idTipoHoja` ASC),
  INDEX `fk_Planta_Continente1_idx` (`Continente_idContinente` ASC),
  INDEX `fk_Planta_ZonaCardinal1_idx` (`ZonaCardinal_idZonaCardinal` ASC),
  INDEX `fk_Planta_Familia1_idx` (`Familia_idFamilia` ASC),
  INDEX `fk_Planta_DeterminadaPor1_idx` (`DeterminadaPor_idDeterminadaPor` ASC),
  INDEX `fk_Planta_NombreCientifico1_idx` (`NombreCientifico_idNombreCientifico` ASC),
  CONSTRAINT `fk_Planta_Forma1`
    FOREIGN KEY (`Forma_idForma`)
    REFERENCES `BD_SIBCATIE`.`Forma` (`idForma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_EstadoSalud1`
    FOREIGN KEY (`EstadoSalud_idEstadoSalud`)
    REFERENCES `BD_SIBCATIE`.`EstadoSalud` (`idEstadoSalud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `BD_SIBCATIE`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_TipoHoja1`
    FOREIGN KEY (`TipoHoja_idTipoHoja`)
    REFERENCES `BD_SIBCATIE`.`TipoHoja` (`idTipoHoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_Continente1`
    FOREIGN KEY (`Continente_idContinente`)
    REFERENCES `BD_SIBCATIE`.`Continente` (`idContinente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_ZonaCardinal1`
    FOREIGN KEY (`ZonaCardinal_idZonaCardinal`)
    REFERENCES `BD_SIBCATIE`.`ZonaCardinal` (`idZonaCardinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_Familia1`
    FOREIGN KEY (`Familia_idFamilia`)
    REFERENCES `BD_SIBCATIE`.`Familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_DeterminadaPor1`
    FOREIGN KEY (`DeterminadaPor_idDeterminadaPor`)
    REFERENCES `BD_SIBCATIE`.`DeterminadaPor` (`idDeterminadaPor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_NombreCientifico1`
    FOREIGN KEY (`NombreCientifico_idNombreCientifico`)
    REFERENCES `BD_SIBCATIE`.`NombreCientifico` (`idNombreCientifico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Uso` (
  `idUso` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idUso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`NombreComun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`NombreComun` (
  `idNombreComun` INT NOT NULL,
  `nombre_comun` VARCHAR(45) NULL,
  `lengua` VARCHAR(45) NULL,
  `Planta_idPlanta` INT NOT NULL,
  PRIMARY KEY (`idNombreComun`, `Planta_idPlanta`),
  INDEX `fk_NombreComun_Planta1_idx` (`Planta_idPlanta` ASC),
  CONSTRAINT `fk_NombreComun_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `BD_SIBCATIE`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Foto` (
  `idFoto` INT NOT NULL,
  `fecha` DATE NULL,
  `latitud` DECIMAL NULL,
  `longitud` DECIMAL NULL,
  `Planta_idPlanta` INT NOT NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idFoto`, `Planta_idPlanta`),
  INDEX `fk_Foto_Planta_idx` (`Planta_idPlanta` ASC),
  CONSTRAINT `fk_Foto_Planta`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `BD_SIBCATIE`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Planta_has_Uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Planta_has_Uso` (
  `Planta_idPlanta` INT NOT NULL,
  `Uso_idUso` INT NOT NULL,
  PRIMARY KEY (`Planta_idPlanta`, `Uso_idUso`),
  INDEX `fk_Planta_has_Uso_Planta1_idx` (`Planta_idPlanta` ASC),
  INDEX `fk_Planta_has_Uso_Uso1_idx` (`Uso_idUso` ASC),
  CONSTRAINT `fk_Planta_has_Uso_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `BD_SIBCATIE`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_has_Uso_Uso1`
    FOREIGN KEY (`Uso_idUso`)
    REFERENCES `BD_SIBCATIE`.`Uso` (`idUso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NULL,
  `activo` VARCHAR(45) NULL,
  `rol` TINYINT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Historial` (
  `idActividad` INT NOT NULL,
  `fecha` DATETIME NULL,
  `accion` VARCHAR(45) NULL,
  `Planta_idPlanta` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idActividad`, `Planta_idPlanta`, `Usuario_idUsuario`),
  INDEX `fk_Historial_Planta1_idx` (`Planta_idPlanta` ASC),
  INDEX `fk_Historial_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Historial_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `BD_SIBCATIE`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historial_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `BD_SIBCATIE`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Visitante` (
  `idVisitante` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idVisitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Consulta` (
  `idConsulta` INT NOT NULL,
  `consulta` TEXT NULL,
  `fecha_consulta` DATETIME NULL,
  `url_foto` VARCHAR(255) NULL,
  `latitud` DECIMAL NULL,
  `longitud` DECIMAL NULL,
  `Consultacol` VARCHAR(45) NULL,
  `Visitante_idVisitante` INT NOT NULL,
  PRIMARY KEY (`idConsulta`, `Visitante_idVisitante`),
  INDEX `fk_Consulta_Visitante1_idx` (`Visitante_idVisitante` ASC),
  CONSTRAINT `fk_Consulta_Visitante1`
    FOREIGN KEY (`Visitante_idVisitante`)
    REFERENCES `BD_SIBCATIE`.`Visitante` (`idVisitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Exportar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Exportar` (
  `idExportar` INT NOT NULL,
  `Planta_idPlanta` INT NOT NULL,
  `Visitante_idVisitante` INT NOT NULL,
  PRIMARY KEY (`idExportar`, `Planta_idPlanta`, `Visitante_idVisitante`),
  INDEX `fk_Exportar_Planta1_idx` (`Planta_idPlanta` ASC),
  INDEX `fk_Exportar_Visitante1_idx` (`Visitante_idVisitante` ASC),
  CONSTRAINT `fk_Exportar_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `BD_SIBCATIE`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exportar_Visitante1`
    FOREIGN KEY (`Visitante_idVisitante`)
    REFERENCES `BD_SIBCATIE`.`Visitante` (`idVisitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SIBCATIE`.`Favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SIBCATIE`.`Favorito` (
  `idFavorito` INT NOT NULL,
  `Planta_idPlanta` INT NOT NULL,
  `Visitante_idVisitante` INT NOT NULL,
  PRIMARY KEY (`idFavorito`, `Planta_idPlanta`, `Visitante_idVisitante`),
  INDEX `fk_Favorito_Planta1_idx` (`Planta_idPlanta` ASC),
  INDEX `fk_Favorito_Visitante1_idx` (`Visitante_idVisitante` ASC),
  CONSTRAINT `fk_Favorito_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `BD_SIBCATIE`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorito_Visitante1`
    FOREIGN KEY (`Visitante_idVisitante`)
    REFERENCES `BD_SIBCATIE`.`Visitante` (`idVisitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
